create database customer_behaviour;
show databases;
use customer_behaviour;
show tables;
select * from customer_data limit 5;

-- Q1 what is the total revenue generated by male vs female customers
select gender , sum(bill_value) as Revenue from customer_data group by gender;

-- Q2 which customers used discount and still purchased more than the average purchase values
select customer_id , bill_value as More_than_AVG from customer_data
where discount_applied = 'yes' and bill_value >= (select avg(bill_value) from customer_data);

-- Q3 which are the top 5 products with highest average review rating
select item_purchased as products,ROUND(AVG(CAST(review_rating AS DECIMAL(10,2))), 2) AS avg_review from customer_data
group by item_purchased order by avg_review desc limit 5;

-- Q4 compare the average purchase amount between standard and express shiping
select shipping_type , round(avg(bill_value),2) as avg_purchase from customer_data
where shipping_type in ('Standard','Express') group by shipping_type ;

-- Q5 Do subscribed customers spent more? compare average spent and total revenue betweeen subscribers and non subscribers
select subscription_status, count(subscription_status) as total , round(avg(bill_value),2) as avg_spent, round(sum(bill_value),2) total_revenue from customer_data
group by subscription_status order by total_revenue desc;

-- Q6 which 5 products have the highest percentage of purchase discounts applied
select item_purchased, count(item_purchased) as total_purchase , discount_applied from customer_data
where discount_applied = 'yes' group by item_purchased order by total_purchase desc limit 5;

select item_purchased,
round(sum(case when discount_applied = 'yes' then 1 else 0 end )/count(*),2) as discount_rate from customer_data
group by item_purchased order by discount_rate desc limit 5;

-- Q7 segment the customers into new, returning, loyal based on their total number of previous purchases and show the count of the each segment
with customer_type as (
select previous_purchases, case
	when previous_purchases between 1 and 13 then 'new'
    when previous_purchases between 14 and 37 then 'returning'
    else 'loyal' 
    end as customer_segment
    from customer_data)
select customer_segment , count(*) as total_customer from customer_type group by customer_segment order by total_customer desc;

-- Q8 what are the top 3 most purchased product within each category
with ranked_items as (
select category, item_purchased, sum(bill_value) as total_sale,
ROW_number() over(partition by category order by sum(bill_value) desc) as top_ranks
from customer_data group by category, item_purchased)
select * from ranked_items where top_ranks <=3 ;

-- Q9 Find the top 3 products (based on total purchase amount) within each category, but only include categories whose total revenue > 30,000
with top_cat as (
select category, item_purchased , sum(bill_value) as total_sale,
row_number() over(partition by category order by sum(bill_value) desc) as top_rank,
sum(sum(bill_value)) over (partition by category )as category_sum
from customer_data group by category , item_purchased)
select * from top_cat where top_rank <= 3 and category_sum >= 30000;

-- Q10 Find Top 2 Products in Each Category with Above-Average Ratings
with top_review as (
select item_purchased , category ,
sum(bill_value) as total_purchase, 
ROUND(avg(cast(review_rating as decimal(10,2))),2) as item_avg_rating,
row_number() over(partition by category order by sum(bill_value) desc) as review_rank
from customer_data group by item_purchased , category),
avg_category as (
select c.category , ROUND(avg(cast(review_rating as decimal(10,2))),2) as avg_category_rating
from customer_data c group by c.category)
select r.* from top_review r join avg_category a on r.category = a.category where r.item_avg_rating > a.avg_category_rating and r.review_rank <=2;

-- Q11 Find Categories Where Top Product Contributes > 40% of Total Sales
WITH sales_summary AS (
    SELECT 
        category,
        item_purchased,
        SUM(bill_value) AS total_sale,
        SUM(SUM(bill_value)) OVER (PARTITION BY category) AS category_total,
        RANK() OVER (PARTITION BY category ORDER BY SUM(bill_value) DESC) AS rnk
    FROM customer_data
    GROUP BY category, item_purchased
)
SELECT category, item_purchased, total_sale, category_total, rnk
FROM sales_summary
WHERE rnk <= 2 and (total_sale / category_total) > 0.4;

-- Q12 Compare Each Item’s Average Rating to Its Category’s Average and the Overall Average
SELECT 
    item_purchased,
    category,
    round(AVG(review_rating),2) AS item_avg,
    round(AVG(AVG(review_rating)) OVER (PARTITION BY category),2) AS cat_avg,
    round(AVG(AVG(review_rating)) OVER (),2) AS overall_avg,
    round(AVG(review_rating) - AVG(AVG(review_rating)) OVER (PARTITION BY category),2) AS diff_from_cat,
    round(AVG(review_rating) - AVG(AVG(review_rating)) OVER (),2) AS diff_from_overall
FROM customer_data
GROUP BY item_purchased, category;

-- Q13 are customers who are repeat buyers (more the 5 previous purchases) also likely to subscribe ?
select subscription_status , count(customer_id) from customer_data
where previous_purchases > 5 group by subscription_status ;

-- Q14 what is revenue rgeneratd by age group
select age_category, sum(bill_value) as total_revenue from customer_data group by age_category order by total_revenue desc;
    
-- Q15 Seasonal Revenue Leaders – But Only for Categories with >10 Unique Products
with seasonal_revenue as (
select item_purchased , category, season,
sum(bill_value) as seasonal_total,
row_number() over(partition by season order by sum(bill_value) desc) as seasonal_rnk
from customer_data group by item_purchased , category, season),
above_10_prod as (
select c.category ,count(distinct item_purchased) item_counts from customer_data c group by c.category having item_counts > 10)
select sr.* from seasonal_revenue sr join above_10_prod ap on ap.category = sr.category where sr.seasonal_rnk <=3 order by sr.seasonal_rnk ;


